### ISSUE TITLE
[Bug] tooltip problem on mobile 

### ISSUE THREAD

**Issue by LeLocTai** [AntonPalmqvist/physically-based-api#6]
Tooltips can't be open in the first section on mobile. Clicking on the **i** open the details panel instead.

It works on the second section, but is clipped by the screen.
![Screenshot_20220819-101241_Firefox Nightly](https://user-images.githubusercontent.com/12182348/185535123-a240d2f6-2ab3-4cc5-873e-6ec1e1602fb2.jpg)

**Comment by AntonPalmqvist** [comment]
Thank you for reporting this!

The mobile experience definitely needs some more love.
I'll close this since this isn't directly related to the database, but rather the front end, which is a separate, closed source, project.
I will note this down however and make sure to adress this in a future update of the website.
